import systemError from "../../Utils/Error/SystemError";




export async function getBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}


export async function getBrands(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}


export async function addBrand(req, res){
try {
    
} catch (error) {
    console.log(error);
    return systemError.sendError(res, error);
}
}


export async function editBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}




export async function deleteBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}






export async function addOrDeleteAcount(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}







export async function getSubBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}



export async function getSubBrands(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}


export async function addSubBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}








export async function editSubBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}


export async function deleteSubBrand(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}



export async function addOrDeleteAcount(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}


export async function getAccount(req, res){
    try {
        
    } catch (error) {
        console.log(error);
        return systemError.sendError(res, error);
    }
}